[package]
name = "aoc-runner-derive"
version = "0.1.0"
authors = ["Gr√©gory Obanos <gregory.obanos@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.13", features = ["extra-traits"] }
quote = "0.6.8"

[features]
default = []
nightly = ["syn/full"]