[package]
name = "aoc-runner"
version = "0.3.0"
authors = ["Gr√©gory Obanos <gregory.obanos@gmail.com>"]
description = "A runner for the Advent of Code"
license = "MIT/Apache-2.0"
repository = "https://github.com/gobanos/aoc-runner"
readme = "README.md"

[dependencies]